// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import { defineConfig, env } from "prisma/config";

const NODE_ENV = process.env.NODE_ENV || "development";

if (NODE_ENV === "development" || NODE_ENV === "test") {
  const { config } = require("dotenv");

  config({
    path: `./.env.${NODE_ENV}`,
  });
}

export default defineConfig({
  schema: "schema.prisma",
  migrations: {
    path: "src/prisma/migrations",
  },
  datasource: {
    url: env("DATABASE_URL")
  },
});
